name: 🎸 Update project on Stepman.AI

on:
  workflow_dispatch:

jobs:
  generate-project:
    if: >-
      ${{ !github.event.repository.is_template }}
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Check object (for debugging only)
        run: |
          cat << OBJECT
          ${{ toJson(github) }}
          OBJECT

      - name: Set up the environment
        uses: ./.github/actions/setup-python-env

      # - name: Run checks
      #   run: make check

      # - name: Remove all templated files in current repository
      #   run: |
      #     find . \( -name "*.jinja" -o -name "*{*" \) -exec rm -r {} +

      - name: Generate project from gh:stepmanai/project-bass
        run: >
          copier copy --vcs-ref main
          --data project_name="${{ github.event.repository.name }}"
          --data project_description="${{ github.event.repository.description }}"
          https://github.com/stepmanai/project-bass.git .

      - name: Create uv.lock file
        run: |
          make install

      - name: Run pre-commit hooks
        run: |
          uv run pre-commit run -a

      - name: Remove project-bass specific files from new project repository post-Copier template generation
        run: |
          find . \( -name 'project-bass*' -or -name 'debug_template.sh' -or -name 'setup-project-on-create.yml' \) -exec rm -r {} +

      # - name: Commit to main branch with formatted changes
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "Created ${{ github.event.repository.name }} project with setup-project-on-create workflow from project-bass."
      #     create_branch: false
      #     commit_user_name: ${{ github.actor }}
      #     commit_user_email: ${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com
